export enum DomainErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  // User - Entity
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_INACTIVE = 'USER_INACTIVE',
  USER_ALREADY_ACTIVE = 'USER_ALREADY_ACTIVE',
  USER_ALREADY_INACTIVE = 'USER_ALREADY_INACTIVE',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USER_ROLE_ALREADY_HAS = 'USER_ROLE_ALREADY_HAS',
  USER_UPDATE_NO_CHANGES_DETECTED = 'USER_UPDATE_NO_CHANGES_DETECTED',

  // Customer - Entity
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  CUSTOMER_ALREADY_ACTIVE = 'CUSTOMER_ALREADY_ACTIVE',
  CUSTOMER_ALREADY_INACTIVE = 'CUSTOMER_ALREADY_INACTIVE',
  CUSTOMER_ALREADY_EXISTS = 'CUSTOMER_ALREADY_EXISTS',
  CUSTOMER_UPDATE_NO_CHANGES_DETECTED = 'CUSTOMER_UPDATE_NO_CHANGES_DETECTED',

  // Sale - Entity
  SALE_NOT_FOUND = 'SALE_NOT_FOUND',
  INVALID_SALE_OPERATION = 'INVALID_SALE_OPERATION',
  SALE_UPDATE_NO_CHANGES_DETECTED = 'SALE_UPDATE_NO_CHANGES_DETECTED',
}
