export enum DomainErrorCode {
  // User - Entity
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_INACTIVE = 'USER_INACTIVE',
  USER_ALREADY_ACTIVE = 'USER_ALREADY_ACTIVE',
  USER_ALREADY_INACTIVE = 'USER_ALREADY_INACTIVE',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USER_ROLE_ALREADY_HAS = 'USER_ROLE_ALREADY_HAS',
  USER_UPDATE_NO_CHANGES_DETECTED = 'USER_UPDATE_NO_CHANGES_DETECTED',

  // User - Email
  USER_EMAIL_REQUIRED = 'USER_EMAIL_REQUIRED',
  USER_EMAIL_INVALID_FORMAT = 'USER_EMAIL_INVALID_FORMAT',

  // User - Hashed Password
  USER_HASHED_PASSWORD_REQUIRED = 'USER_HASHED_PASSWORD_REQUIRED',
  USER_HASHED_PASSWORD_TOO_LONG = 'USER_HASHED_PASSWORD_TOO_LONG',
  USER_HASHED_PASSWORD_INVALID_FORMAT = 'USER_HASHED_PASSWORD_INVALID_FORMAT',

  // User - Id
  USER_ID_REQUIRED = 'USER_ID_REQUIRED',
  USER_ID_INVALID_FORMAT = 'USER_ID_INVALID_FORMAT',

  // User - Name
  USER_NAME_REQUIRED = 'USER_NAME_REQUIRED',
  USER_NAME_TOO_LONG = 'USER_NAME_TOO_LONG',
  USER_NAME_INVALID_FORMAT = 'USER_NAME_INVALID_FORMAT',

  // User - Role
  USER_ROLE_REQUIRED = 'USER_ROLE_REQUIRED',
  USER_ROLE_INVALID = 'USER_ROLE_INVALID',

  // User - Status
  USER_STATUS_REQUIRED = 'USER_STATUS_REQUIRED',
  USER_STATUS_INVALID = 'USER_STATUS_INVALID',

  // Shared - Paginated Result
  PAGINATED_RESULT_DATA_INVALID = 'PAGINATED_RESULT_DATA_INVALID',
  PAGINATED_RESULT_TOTAL_INVALID = 'PAGINATED_RESULT_TOTAL_INVALID',

  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
}
