export enum DomainErrorCode {
  // User - Entity
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_INACTIVE = 'USER_INACTIVE',
  USER_ALREADY_ACTIVE = 'USER_ALREADY_ACTIVE',
  USER_ALREADY_INACTIVE = 'USER_ALREADY_INACTIVE',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USER_ROLE_ALREADY_HAS = 'USER_ROLE_ALREADY_HAS',
  USER_UPDATE_NO_CHANGES_DETECTED = 'USER_UPDATE_NO_CHANGES_DETECTED',

  // User - Email
  USER_EMAIL_REQUIRED = 'USER_EMAIL_REQUIRED',
  USER_EMAIL_INVALID_FORMAT = 'USER_EMAIL_INVALID_FORMAT',

  // User - Hashed Password
  USER_HASHED_PASSWORD_REQUIRED = 'USER_HASHED_PASSWORD_REQUIRED',
  USER_HASHED_PASSWORD_TOO_LONG = 'USER_HASHED_PASSWORD_TOO_LONG',
  USER_HASHED_PASSWORD_INVALID_FORMAT = 'USER_HASHED_PASSWORD_INVALID_FORMAT',

  // User - Id
  USER_ID_REQUIRED = 'USER_ID_REQUIRED',
  USER_ID_INVALID_FORMAT = 'USER_ID_INVALID_FORMAT',

  // User - Name
  USER_NAME_REQUIRED = 'USER_NAME_REQUIRED',
  USER_NAME_TOO_LONG = 'USER_NAME_TOO_LONG',
  USER_NAME_INVALID_FORMAT = 'USER_NAME_INVALID_FORMAT',

  // User - Role
  USER_ROLE_REQUIRED = 'USER_ROLE_REQUIRED',
  USER_ROLE_INVALID = 'USER_ROLE_INVALID',

  // User - Status
  USER_STATUS_REQUIRED = 'USER_STATUS_REQUIRED',
  USER_STATUS_INVALID = 'USER_STATUS_INVALID',

  // Shared - Paginated Result
  PAGINATED_RESULT_DATA_INVALID = 'PAGINATED_RESULT_DATA_INVALID',
  PAGINATED_RESULT_TOTAL_INVALID = 'PAGINATED_RESULT_TOTAL_INVALID',

  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  // Customer - Entity
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  CUSTOMER_ALREADY_ACTIVE = 'CUSTOMER_ALREADY_ACTIVE',
  CUSTOMER_ALREADY_INACTIVE = 'CUSTOMER_ALREADY_INACTIVE',
  CUSTOMER_ALREADY_EXISTS = 'CUSTOMER_ALREADY_EXISTS',
  CUSTOMER_UPDATE_NO_CHANGES_DETECTED = 'CUSTOMER_UPDATE_NO_CHANGES_DETECTED',

  // Customer - Id
  CUSTOMER_ID_REQUIRED = 'CUSTOMER_ID_REQUIRED',
  CUSTOMER_ID_INVALID_FORMAT = 'CUSTOMER_ID_INVALID_FORMAT',

  // Customer - Name
  CUSTOMER_NAME_REQUIRED = 'CUSTOMER_NAME_REQUIRED',
  CUSTOMER_NAME_TOO_LONG = 'CUSTOMER_NAME_TOO_LONG',
  CUSTOMER_NAME_INVALID_FORMAT = 'CUSTOMER_NAME_INVALID_FORMAT',

  // Customer - Type Document
  CUSTOMER_TYPE_DOCUMENT_REQUIRED = 'CUSTOMER_TYPE_DOCUMENT_REQUIRED',
  CUSTOMER_TYPE_DOCUMENT_INVALID = 'CUSTOMER_TYPE_DOCUMENT_INVALID',

  // Customer - Num Document
  CUSTOMER_NUM_DOCUMENT_REQUIRED = 'CUSTOMER_NUM_DOCUMENT_REQUIRED',
  CUSTOMER_NUM_DOCUMENT_INVALID_FORMAT = 'CUSTOMER_NUM_DOCUMENT_INVALID_FORMAT',

  // Customer - Phone
  CUSTOMER_PHONE_REQUIRED = 'CUSTOMER_PHONE_REQUIRED',
  CUSTOMER_PHONE_INVALID_FORMAT = 'CUSTOMER_PHONE_INVALID_FORMAT',

  // Customer - Email
  CUSTOMER_EMAIL_INVALID_FORMAT = 'CUSTOMER_EMAIL_INVALID_FORMAT',

  // Customer - Address
  CUSTOMER_ADDRESS_REQUIRED = 'CUSTOMER_ADDRESS_REQUIRED',
  CUSTOMER_ADDRESS_TOO_LONG = 'CUSTOMER_ADDRESS_TOO_LONG',
  CUSTOMER_ADDRESS_INVALID_FORMAT = 'CUSTOMER_ADDRESS_INVALID_FORMAT',

  // Customer - Status
  CUSTOMER_STATUS_REQUIRED = 'CUSTOMER_STATUS_REQUIRED',
  CUSTOMER_STATUS_INVALID = 'CUSTOMER_STATUS_INVALID',

  // Sale - Entity
  SALE_NOT_FOUND = 'SALE_NOT_FOUND',
  INVALID_SALE_OPERATION = 'INVALID_SALE_OPERATION',
  SALE_UPDATE_NO_CHANGES_DETECTED = 'SALE_UPDATE_NO_CHANGES_DETECTED',

  // Sale - Id
  SALE_ID_REQUIRED = 'SALE_ID_REQUIRED',
  SALE_ID_INVALID_FORMAT = 'SALE_ID_INVALID_FORMAT',

  // Sale - Kilograms
  SALE_KILOGRAMS_REQUIRED = 'SALE_KILOGRAMS_REQUIRED',
  SALE_KILOGRAMS_INVALID_FORMAT = 'SALE_KILOGRAMS_INVALID_FORMAT',
  SALE_KILOGRAMS_MUST_BE_POSITIVE = 'SALE_KILOGRAMS_MUST_BE_POSITIVE',

  // Sale - Price Per Kilogram
  SALE_PRICE_PER_KILOGRAM_REQUIRED = 'SALE_PRICE_PER_KILOGRAM_REQUIRED',
  SALE_PRICE_PER_KILOGRAM_INVALID_FORMAT = 'SALE_PRICE_PER_KILOGRAM_INVALID_FORMAT',
  SALE_PRICE_PER_KILOGRAM_MUST_BE_POSITIVE = 'SALE_PRICE_PER_KILOGRAM_MUST_BE_POSITIVE',

  // Sale - Total Amount
  SALE_TOTAL_AMOUNT_REQUIRED = 'SALE_TOTAL_AMOUNT_REQUIRED',
  SALE_TOTAL_AMOUNT_INVALID_FORMAT = 'SALE_TOTAL_AMOUNT_INVALID_FORMAT',

  // Sale - Payment Status
  SALE_PAYMENT_STATUS_REQUIRED = 'SALE_PAYMENT_STATUS_REQUIRED',
  SALE_PAYMENT_STATUS_INVALID = 'SALE_PAYMENT_STATUS_INVALID',
}
